version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8888:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pizza
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1Iwltbr1
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    ports:
      - '3333:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1Iwltbr1
      MYSQL_DATABASE: pizza
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10